### ISSUE TITLE
No plugin found for prefix 'sonar-break'

### ISSUE THREAD

**Issue by raderio** [sgoertzen/sonar-break-maven-plugin#13]
No plugin found for prefix 'sonar-break'
Can you provide a full example of pom?

**Comment by sgoertzen** [comment]
Check the integration tests folder in the repo.  It has two different projects with poms.  If you are still having issues go ahead and paste your pom in here and I can review it.

**Comment by raderio** [comment]
I removed
```
<dependencies>
    <dependency>
        <groupId>com.github.sgoertzen</groupId>
        <artifactId>sonarbreak</artifactId>
        <version>1.1.3</version>
    </dependency>
</dependencies>
```

now it' working, thanks

**Comment by sgoertzen** [comment]
If you don't include that dependency you won't be including or running this
plugin.

**Comment by ec-wagner** [comment]
@sgoertzen  seems like defining dependency is not required but what is required it to make following change:

```
<plugin>
  <groupId>com.github.sgoertzen</groupId>
  <artifactId>sonar-break-maven-plugin</artifactId>
  <version>1.2.5</version>
</plugin>
```
