### ISSUE TITLE
Can you put 1.2.5 in to https://mvnrepository.com/artifact/com.github.sgoertzen/sonar-break-maven-plugin?

### ISSUE THREAD

**Issue by yasinmustafa** [sgoertzen/sonar-break-maven-plugin#43]
Apologies because this is not really an issue, but can you move 1.2.5 into mvnrepository please?

Just that 1.2.5 works for the version of sonar I'm using (but 1.2.3 doesn't)

Thanks,

Yasin

**Comment by sgoertzen** [comment]
Thanks for the reminder.  Just pushed 1.2.5 up.  It should show up within 24 hours.

**Comment by yasinmustafa** [comment]
Hi, can you double check on this as I cant see it in mvn central yet

**Comment by sgoertzen** [comment]
It is showing up for me: https://search.maven.org/#artifactdetails%7Ccom.github.sgoertzen%7Csonar-break-maven-plugin%7C1.2.5%7C
